### PR TITLE
dry out fix

### PR DESCRIPTION
**Pull request by zephyrside**
fixed dry out's pulse width in a few frames

### CODE REVIEW

**Comment by jaezudev** [comment]
fix ur merge conflicts first
oh also get your ass in the discord, all of the discussion is happening in there

**Review by jaezudev — CHANGES_REQUESTED** [review]
fix the merge conflicts

**Comment by zephyrside** [comment]
alr, will fix real quick
also i can't get back on discord just yet, will soon though :+1:

**Comment by zephyrside** [comment]
misclick

**Comment by jaezudev** [comment]
lmao

**Pull request closed without merging**
